services:
  filebrowser:
    user: 0:0
    volumes:
      - ../../storage:/storage:rw
      - ../../backup:/backup:rw
      - ./config.yaml:/home/filebrowser/config.yaml
    ports:
      - '8002:80'
    image: gtstef/filebrowser
    restart: unless-stopped
