server:
  port: 80
  sources:
    - path: "/storage"
    - path: "/files"
auth:
  methods:
    noauth: true
frontend:
  name: "DiwanSync"
  styling:
    customCSS: "reduce-rounded-corners.css"
userDefaults:
  darkMode: false
  viewMode: "list"
  showHidden: true
  quickDownload: true
  stickySidebar: true
  editorQuickSave: true