#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  002-immich-server:
    container_name: 002-immich-server
    image: ghcr.io/immich-app/immich-server:${VERSION_IMMICH}
    volumes:
      - ../../storage/volumes/002-immich/upload:/usr/src/app/upload
      - ../../storage/media/002-immich/library:/usr/src/app/upload/library
      - ./configuration.yml:/config/configuration.yml:ro
      - ../../scripts/compile.sh:/config/compile.sh:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["/bin/sh", "-c", "/config/compile.sh && exec start.sh"]
    env_file:
      - ../../storage/env/004-dyngress.env
      - ../../storage/env/002-immich.env
    environment:
      IMMICH_CONFIG_FILE: /compiled/configuration.yml
      DB_HOSTNAME: 002-immich-postgres
      REDIS_HOSTNAME: 002-immich-redis
    ports:
      - '8002:2283'
    depends_on:
      - 002-immich-redis
      - 002-immich-postgres
    restart: always
    # noinspection ComposeMissingKeys
    # healthcheck is implemented by the image
    healthcheck:
      disable: false

  002-immich-machine-learning:
    container_name: 002-immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${VERSION_IMMICH}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - ../../storage/env/004-dyngress.env
      - ../../storage/env/002-immich.env
    restart: always
    # noinspection ComposeMissingKeys
    # healthcheck is implemented by the image
    healthcheck:
      disable: false

  002-immich-redis:
    container_name: 002-immich-redis
    image: docker.io/redis:${VERSION_REDIS}
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  002-immich-postgres:
    container_name: 002-immich-postgres
    image: ghcr.io/immich-app/postgres:${VERSION_POSTGRES}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ../../storage/volumes/002-immich/data:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
