 services:
  004-nginx:
    profiles: ["004-nginx"]
    container_name: nginx-proxy-manager
    image: 'docker.io/jc21/nginx-proxy-manager:2.15.1'
    restart: unless-stopped
    ports:
      - '80:80'
      - '8004:81'
      - '443:443'
    volumes:
      - ../../storage/volumes/004-nginx/data:/data
      - ../../storage/volumes/004-nginx/letsencrypt:/etc/letsencrypt
