server:
  port: 80
  sources:
    - path: "/mnt/storage"
    - path: "/mnt/backup"
auth:
  methods:
    noauth: true
frontend:
  name: "DiwanStorage"
userDefaults:
  darkMode: false
  viewMode: "list"
