services:
  filebrowser:
    user: 0:0
    volumes:
      - /mnt:/mnt:rw
      - ./config.yaml:/home/filebrowser/config.yaml
    ports:
      - '8000:80'
    image: gtstef/filebrowser
    restart: unless-stopped
