services:
    filebrowser:
        container_name: filebrowser
        user: 0:0
        command: ["--noauth"]
        volumes:
            - /mnt:/srv:rw
            - ./branding:/branding
            - ./config.json:/.filebrowser.json
            - ./filebrowser/database.db:/database.db
        ports:
            - 8000:80
        image: filebrowser/filebrowser
        restart: unless-stopped

