services:
  006-ddns:
    profiles: ["006-ddns"]
    image: qmcgaw/ddns-updater:v2.10.0
    container_name: ddns-updater
    user: 0:0
    network_mode: bridge
    ports:
      - 8006:8000/tcp
    volumes:
      - ../../storage/volumes/006-ddns/data:/updater/data
    environment:
      -  PERIOD=5m
      -  IP_METHOD=cycle
      -  IPV4_METHOD=cycle
      -  IPV6_METHOD=cycle
      -  HTTP_TIMEOUT=10s
      -  LISTENING_PORT=8006
      -  ROOT_URL=/
    restart: always
