services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: sync.storage
    volumes:
      - /mnt/storage:/storage
      - ./syncthing:/var/syncthing
    environment:
      - PUID=0
      - PGID=0
    ports:
      - 8000:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped

